### ISSUE TITLE
Youtube Strictness not saving

### ISSUE THREAD

**Issue by orbitalchicken** [serv-inc/safe-search#15] opened 2018-11-14 05:28 UTC
The youtube setting always come back to "lenient". I save, close the module tab or close firefox, then, when I come back, the setting is still "lenient". 
(By the way, I do not understant what is lenient)

**Comment by serv-inc** [comment] 2018-11-15 10:58
Yes, it seems like this is broken. Thanks for reporting it.

**Comment by serv-inc** [comment] 2018-11-15 10:58
PS: lenient: do not show adult content, but do not enable YouTube's built-in extra filters.

**Comment by Nomen-Heroum** [comment] 2019-01-28 04:37
I have a similar issue. I want the setting on lenient, but it keeps resetting to moderate. When I reset it to lenient the change does register and I can use YouTube like normal, but upon restart of Firefox it goes back to moderate.

This is an issue for me because I'd like to restrict access to about:addons in the policies.json file, but it's just not viable as long as I have to keep resetting the YouTube setting.

**Comment by serv-inc** [comment] 2019-02-21 07:55
This is due to the specific way settings are saved. It seems fixable, but with some effort. As a workaround, you should be able to remove the extension's data (removing the extension should suffice), then reinstall it. 

For a fix, please give me a bit of time to fix this thoroughly.

**Comment by serv-inc** [comment] 2019-02-24 16:05
@orbitalchicken  @Nomen-Heroum : please check if version 4.5.1 fixes this.

**Comment by Nomen-Heroum** [comment] 2019-02-26 17:05
I'm afraid the bug still persists, even after removing and reinstalling the addon. Maybe 4.5.1 resolves the issues for new users though—I'm not sure removing the addon gets rid of all the saved data. 

I had a look in ~/.mozilla/firefox/2dbxw24t.default/ which is where Firefox stores all its data AFAIK (I'm on Ubuntu 18.04), and in both ./browser-extension-data/ and ./extension-data/ I found data from old extensions that I've long ago uninstalled. I wasn't able to identify where data for Enforce Safe Search is stored, though many of the folders in these two directories have generic names like {9da90a70-c879-44a0-b991-0fd9145ae87e}. Does one of these contain the settings for this extension? If not, where does the extension store its data?

**Comment by serv-inc** [comment] 2019-02-27 06:30
@Nomen-Heroum :Thank you for testing this. The folder name should be `{b52acdad-e4a6-44da-afc9-9bd22572db99}`. 
It could help debugging if you were willing to zip and upload this folder to GitHub. Just drag and drop into the text box.

**Comment by Nomen-Heroum** [comment] 2019-03-01 18:23
Glad to help! The folder ~/.mozilla/firefox/2dbxw24t.default/browser-extension-data/
{b52acdad-e4a6-44da-afc9-9bd22572db99} exists but it is empty. I did find a .xpi file in ~/.mozilla/firefox/2dbxw24t.default/extensions though, which has the same name:

[{b52acdad-e4a6-44da-afc9-9bd22572db99}.zip](https://github.com/serv-inc/safe-search/files/2920485/b52acdad-e4a6-44da-afc9-9bd22572db99.zip)

I tried removing the extension via Firefox, then removing aforementioned empty folder and .xpi file, then reinstalling the extension. The issue persists, and both the folder and the .xpi file have come back. I used `diff` to confirm that the new .xpi file is indeed identical to the old one I posted above.

I then tried removing the .xpi file while the extension was still installed. For some reason the extension remained functional and the YouTube strictness setting could still be changed (I confirmed it actually affected YouTube), but after restarting Firefox, the extension was no longer installed (and the effects of it were gone).

Hope that helps! Not sure if this is a Linux specific issue, if you want I can hop on Windows later and see how the extension behaves there.

**Comment by serv-inc** [comment] 2019-03-03 07:52
Ok, this coud be reproduced on a clean install. Let's try and debug this...

**Comment by serv-inc** [comment] 2019-03-06 11:40
At least for a clean install, this seems to be fixed in https://github.com/serv-inc/safe-search/commit/8888cdd2ada971132b5b40688fa872cfd453f01e. Please reply or reopen this issue if the problem persists for existing installations.

**Closed by serv-inc** 2019-03-06 11:40 UTC
Labels: bug

**Comment by Nomen-Heroum** [comment] 2019-03-06 17:30
Just want to confirm that the issue is fixed in version 4.6.0 on my existing installation. No reinstall required!

Thanks for the fix, much appreciated.
