### ISSUE TITLE
Complete Failure in Chrome browser

### ISSUE THREAD

**Issue by amzaf** [serv-inc/safe-search#18] opened 2019-04-17 00:45 UTC
No enforcement at all in Chrome browser.
P.S. First filed the bug for duckduckgo, then checked vimeo, then cross-checked on both Windows and macOS. The extension is not working at all.

**Comment by serv-inc** [comment] 2019-04-18 14:28
Thanks for the feedback. It should work again on DDG in 4.6.1 with another mechanism. 

Re all sites: Weirdly enough, it still seems to work in Firefox, so maybe Chrome changed some things internally... thanks for the update though. Let me try and debug this.

**Comment by serv-inc** [comment] 2019-04-18 16:16
Should work again for Bing with a different method on 4.6.2.

**Comment by serv-inc** [comment] 2019-04-18 16:23
Hmm, it still worked for vimeo for me. Could you please double-check? Steps to reproduce

1. search e.g. por* on vimeo
2. click "mature content filter"
3. try to click "Apply", but nothing happens

**Comment by oskariot** [comment] 2019-04-28 19:46
I confirm, it recently stopped working on Chromium.

**Comment by serv-inc** [comment] 2019-04-29 09:34
Thank you for the confirmation. Could you please say what does and does not work?

**Comment by oskariot** [comment] 2019-04-29 11:25
My version of the browser is:
74.0.3729.108 (Official) Built on Ubuntu, running on Ubuntu 16.04 (64-bits).
I have the newest version of Enforce Safe Search: 4.6.2.

Although I have the extension on I can still toggle the Safe Search off/on.
Moreover clearing the cookies disables the Safe Search. 
It works perfectly on Firefox and used to work on Chromium until recently.

**Comment by serv-inc** [comment] 2019-04-29 11:28
Thank you. Does this happen on all sites, or only on some of them?

**Comment by serv-inc** [comment] 2019-04-30 05:29
DuckDuckGo should be fixed. Please double-check and comment if still broken. Which other sites are broken for you? (Google just seemed to work)

**Comment by serv-inc** [comment] 2019-05-01 09:11
Duckduckgo seems to be fixed a well as possible in 4.7.1. 

@amzaf : as many other pages seem to work, this issue is now closed. Please list specific pages as separate issues.

**Closed by serv-inc** 2019-05-01 09:11 UTC
Labels: bug

**Comment by amzaf** [comment] 2019-05-01 15:29
@serv-inc Thank you. At first, it wasn't working. Had to clear the cache and reinstall the extension.

**Comment by serv-inc** [comment] 2019-05-02 09:43
@amzaf : good to know that it works for you. Sometimes it only works on the second try after installation (but every one thereafter hopefully). So it's only "as well as possible".
